config firewall address
    edit "BR1_LAN"
        set subnet 10.10.63.0 255.255.255.0
    next
    edit "BR2_LAN"
        set subnet 10.10.64.0 255.255.255.0
    next
end

config system sdwan
    set status enable

    config zone
        edit "ADVPN_OVERLAY"
        next
    end

    config members
        edit 1
            set interface "Overlay1_INET"
            set zone "ADVPN_OVERLAY"
        next
        edit 2
            set interface "Overlay2_MPLS"
            set zone "ADVPN_OVERLAY"
        next
        edit 3
            set interface "Overlay3_INET"
            set zone "ADVPN_OVERLAY"
        next
        edit 4
            set interface "Overlay4_MPLS"
            set zone "ADVPN_OVERLAY"
        next
    end

    config health-check
        edit "SLA_HUB1_INET"
            set server "172.16.1.1"
            set protocol ping
            set members 1
            set interval 500
            set failtime 3
            set recoverytime 3
        next
        edit "SLA_HUB1_MPLS"
            set server "172.16.2.1"
            set protocol ping
            set members 2
            set interval 500
            set failtime 3
            set recoverytime 3
        next
        edit "SLA_HUB2_INET"
            set server "172.16.3.1"
            set protocol ping
            set members 3
            set interval 500
            set failtime 3
            set recoverytime 3
        next
        edit "SLA_HUB2_MPLS"
            set server "172.16.4.1"
            set protocol ping
            set members 4
            set interval 500
            set failtime 3
            set recoverytime 3
        next
    end

    config service
        edit 10
            set name "BR1_to_BR2_ADVPN"
            set mode priority
            set src "BR1_LAN"
            set dst "BR2_LAN"
            set health-check "SLA_HUB1_INET" "SLA_HUB1_MPLS" "SLA_HUB2_INET" "SLA_HUB2_MPLS"
            set priority-members 1 2 3 4
        next
    end
end

config firewall policy
    edit 0
        set name "LAN_to_ADVPN_OVERLAY"
        set srcintf "port5"
        set dstintf "ADVPN_OVERLAY"
        set srcaddr "BR1_LAN"
        set dstaddr "BR2_LAN"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat disable
        set logtraffic all
    next
    edit 0
        set name "ADVPN_OVERLAY_to_LAN"
        set srcintf "ADVPN_OVERLAY"
        set dstintf "port5"
        set srcaddr "BR2_LAN"
        set dstaddr "BR1_LAN"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat disable
        set logtraffic all
    next
end
