diagnose sys sdwan member
diagnose sys sdwan health-check
diagnose sys sdwan service4
diagnose firewall proute list

get router info routing-table details 10.10.64.0
get router info routing-table details 10.10.63.0
get router info routing-table bgp | grep port1

diagnose vpn ike gateway list | grep -A40 -B5 BR2

diagnose sys session filter clear
diagnose sys session filter proto 1
diagnose sys session filter dst 10.10.64.2
diagnose sys session list
